### ISSUE TITLE
calc_friction_factor

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/WaterModels.jl#14]
I suggest breaking this out into into two functions one for hazen williams and one darcy weisbach.  Then, these functions get called depending on the pipeflow equation that is added.  In general, we don't store calculated values in the data unless it is an O(n) operation (or worse).... this prevents inevitable bugs where a calculated value gets out of sync with the data used to compute the calculated value. (see how we compute conductance and suscpetance in PowerModels and friction factors in GasModels)

**Comment by ccoffrin** [comment]
As a clarification, in PowerModels *no* calculated values are stored in in the data model.  O(1) calculated values are done in the constraint templates; O(n) calculated values are stored in ref.
