### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/WaterModels.jl#19]
I saw the request to Install AppVeyor.  Do you have a specific need for windows CI?  If not, I would skip it.  If so, is Travis and option?  There is basic support for windows as far as I know.

**Comment by tasseff** [comment]
I thought it would be good to add for completeness. Why skip it? To my knowledge, AppVeyor is the standard for Windows builds. I did see [your post](https://discourse.julialang.org/t/travis-windows-builds-of-julia/18208) discussing Travis-based Windows builds, but I also saw that [JuMP is/was using AppVeyor at some point](https://github.com/JuliaOpt/JuMP.jl/blob/master/appveyor.yml), although the build status is not being shown in their README.

**Comment by ccoffrin** [comment]
Because Julia is interpreted, CI on Linux should be sufficient, in theory.  In the past we have tested on OS X as well, due to binary dependencies and minor inconsistencies in the numerics of the solvers.  With the new binary builder system these issues seem to be mitigated.  However there may be a case for testing on all platforms before making a release.

> Why skip it?

Every new tool we integrate into our dev stack increases maintenance overhead and skill development burden on the team.  The leaner we can be on this the better.  So far, I am not seeing an added value that would outweigh these overheads.

**Comment by tasseff** [comment]
Fair enough, thank you for the explanation. I will forego Windows testing for the time being.
