### ISSUE TITLE
fix epanet parser

### ISSUE THREAD

**Issue by claytonpbarrows** [lanl-ansi/WaterModels.jl#2]
the epanet parser isn't loaded by default when running`include("src/WaterModels_linux.jl")`. Also, the parser appears to be nonfunctional for anything but a basic '.inp' file.

**Comment by rb004f** [comment]
Thansks @claytonpbarrows - This code is still in the very early stages, but we hope to make progress in the next several months (@hskkanth)

**Comment by claytonpbarrows** [comment]
I'll try to address this issue in a pull request in the next couple days. I have a working prototype, but I need to do some more testing.
