### ISSUE TITLE
Release v0.0.1

### ISSUE THREAD

**Issue by tasseff** [lanl-ansi/WaterModels.jl#20]
@JuliaRegistrator register()

**Comment by tasseff** [comment]
@JuliaRegistrator register()

**Comment by tasseff** [comment]
@JuliaRegistrator register()

**Comment by ccoffrin** [comment]
These have been installed now.  Also gave you Admin on this repo so that you can control these things.

**Comment by ccoffrin** [comment]
@JuliaRegistrator register()

**Comment by tasseff** [comment]
Thanks @ccoffrin!
