### ISSUE TITLE
Support non-integer component IDs

### ISSUE THREAD

**Issue by tasseff** [lanl-ansi/WaterModels.jl#24]
Currently, all component IDs are assumed to be integer upon the reading of network data. These IDs are then used identically throughout various model building and solution routines. However, many EPANET input files contain component IDs that are non-integer (i.e., they contain combinations of characters and numbers). For this reason, WaterModels.jl should support network encodings that assume string-like component IDs.

Internally, in the modeling routines and the `ref` structure, corresponding integer IDs should be used that map to each component. The method for assigning these integer IDs should return deterministic mappings when repeatedly called. When the solution to the model is obtained, solution data should be printed with respect to the original (string-like) component IDs.

This could be most easily accomplished through the addition of an integer `index` field to the network components when reading in data (e.g., in [`src/io/epanet.jl`]). A string `id` field could then be used to provide a mapping from the integer to the string. However, reading in data that modifies the network may be more tricky. In this case, the initial network (e.g., from an EPANET input file) should always be constructed first. Then, modifications can be applied on top of the existing network to ensure changes are always made to the correct components.

**Comment by ccoffrin** [comment]
In all infrastructure model packages component ids are ints.  The "name" and "source_id" fields can be used for non-int component ids.

**Comment by tasseff** [comment]
Thanks! I guess `source_id` is what I was after. To be sure, you would recommend assigning integer IDs (`index` values) at the time the file is read?

**Comment by tasseff** [comment]
Also, is there any convention for assigning `index` values? Do you use any sort method on the `source_id` values before assigning them?

**Comment by ccoffrin** [comment]
At the moment the int id convention is as follows: if the source data uses integer ids, use these ids as our ids.  If not, we number the components from 1 to n based on the order they appear in the file.  At least in power network data most tables have a natural table interoperation so 1 to n is analogous to row id in the table.
