### ISSUE TITLE
Print Summary Support

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/WaterModels.jl#40]
The data dict should be compatible with `InfrastructureModels.print_summary`.  The use of `nothing` seems to be an issue, there may be a bug in InfrastructureModels.

WaterModels should also extend the `print_summary` to provide some package specific options.  For example see, https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/data.jl#L178

**Comment by tasseff** [comment]
Drop every key in each data dictionary where `nothing` is the value.

**Comment by ccoffrin** [comment]
@tasseff I think this is fixed?
