### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/WaterModels.jl#42]
PowerModels has standardized around the post-fix values `_fr` and `_to` for edge-like components.  Following this we might change `f_id/t_id` to `node_fr/node_to`.

**Comment by ccoffrin** [comment]
The `title` field in the dict root can also be mapped to a standard infrastructure models field like `name` or `description`.

**Comment by ccoffrin** [comment]
Let's discuss `status` values of `0/1` instead of strings.

**Comment by ccoffrin** [comment]
InfrastructureModels assumes each component has an unique int id in the field called "index".  I think "id" should be updated to "index".

**Comment by ccoffrin** [comment]
We should discuss if component names should be singular or plural.

**Comment by ccoffrin** [comment]
Follow the guide lines of https://github.com/lanl-ansi/PowerModels.jl/issues/538

**Comment by ccoffrin** [comment]
optional kwarg for network id should be `nw` not `n`.

**Comment by tasseff** [comment]
> The `title` field in the dict root can also be mapped to a standard infrastructure models field like `name` or `description`.

This has been addressed.

**Comment by tasseff** [comment]
> We should discuss if component names should be singular or plural.

I think everything should be singular. That's the standard for databases, anyway. This seems to mostly be true for PowerModels, too. If you agree, I'll work toward this.

**Comment by tasseff** [comment]
> PowerModels has standardized around the post-fix values `_fr` and `_to` for edge-like components. Following this we might change `f_id/t_id` to `node_fr/node_to`.

This has been addressed in 69b841d.

**Comment by tasseff** [comment]
> InfrastructureModels assumes each component has an unique int id in the field called "index". I think "id" should be updated to "index".

This has been addressed in 5f4ccc2.

**Comment by ccoffrin** [comment]
@tasseff, I also prefer singular by default with a rare exception if needed.  We can make this a standard across infrastructure models if you like.

**Comment by tasseff** [comment]
Sounds like a good idea to me!

**Comment by tasseff** [comment]
@ccoffrin, I think 569a7ab finishes up the naming convention changes discussed in this issue. We can address more specific changes that come up in separate issues.

**Comment by ccoffrin** [comment]
Look correct to me, I'll close this one!
