### ISSUE TITLE
Build Ref Updates

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/WaterModels.jl#48]
- [x] Add node-based arc/link lookup lists so that flow balance constraints are not quadratic
- [x] filter out inactive components (i.e. status values)
- [x] update to improved `build_ref` design, https://github.com/lanl-ansi/PowerModels.jl/pull/505

**Comment by tasseff** [comment]
Break out "filter out inactive components (i.e. status values)" into a separate issue.
