### ISSUE TITLE
Tidy up use of Enumerate

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/WaterModels.jl#51]
We should try to avoid things like, `enumerate(ref(wm, n, :resistance, a))` in favor of things like `ref(wm, n, :resistance)`.

**Comment by tasseff** [comment]
For variables for like `qp_ne` and `qn_ne`, have these be indexed (possibly) by tuples of resistance ID and link ID.

**Comment by tasseff** [comment]
Also, consider putting resistance values inside of `:pipes` objects.
