### ISSUE TITLE
Time Series Block

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/WaterModels.jl#58]
At the least this block needs an integer specifying how many items each array will have.  It would also benefit from a `time_elapsed` parameter and any other metadata that might come out of the source data.

**Comment by ccoffrin** [comment]
In terms of testing this feature the richmond dataset seems to a nice small cases with some time series data.  However, when I try to run the base case with `run_wf(richmond_skeleton_data, CNLPWaterModel, ipopt)` I get `ERROR: KeyError: key "diameter" not found`?

**Comment by ccoffrin** [comment]
In the  richmond dataset  `data["time_series"]["reservoirs"]` has 11 items but the network data only has 1.

**Comment by tasseff** [comment]
`time_elapsed` will be `time_step`. I will include a `time_series` when there are time series of length greater than one and not using the default time pattern ("1").

**Comment by ccoffrin** [comment]
@tasseff I think this is all set.
