### ISSUE TITLE
Move relevant unit conversions and constant calculations to constraint_template.jl.

### ISSUE THREAD

**Issue by tasseff** [lanl-ansi/WaterModels.jl#9]
A lot of data is being unnecessarily precomputed and stored in `ref`. The data is later used when constructing individual constraints. Much of this should instead be done within `src/core/constraint_template.jl`.

**Comment by ccoffrin** [comment]
Take note one of the per unit conventions in infrastructure models.  Unit conversion is typically done while reading in the data.  After that the code assumes some standard units, which are usually not non-dimensional.

**Comment by tasseff** [comment]
All parameters are now converted to SI base units when reading in an EPANET file. User-defined JSON input assumes SI base units.
